### ISSUE TITLE
Groupsize crash

### ISSUE THREAD

**Issue by aaronlidman** [aaronlidman/openstreetPOIs#3]
Setting the --groupsize option crashes multiprocessing.join(). Probably missed something from the recent rename commit. Leaving it as default works fine.

**Comment by aaronlidman** [comment]
This seems to be a more general problem on Ubuntu 13.04. I've been running against 12.10 to this point which worked fine, but I went back and checked and it seems 13.04 never worked with any version in the past. Luckily it's only in the final .join step.

```
Traceback (most recent call last):
  File "osmpois.py", line 336, in <module>
    process(output)
  File "osmpois.py", line 199, in process
    pool.join()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 461, in join
    p.join()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
```

**Comment by aaronlidman** [comment]
Weird little issue. Not entirely sure what's going on maybe garbage collection? but the process seems to wait because it thinks there are items in the queue when there are not.

The queue originates from various processes and gets sent back to the parent process constantly. It bulks up and gets consumed while the various children keep running and adding to the queue. When the children finish, multiprocessing waits for the queue to be completely consumed before joining together all the children and removing their processes. For some reason multiprocessing hasn't been getting that signal back (that the queue is empty) and just waits and waits. In the consumer (write()) we're constantly dealing with queue.empty() and it reports correctly there on it's own. The consumer doesn't return unless the queue is completely done so I trust it enough to terminate processes if necessary.

I've just brought an artificial queue.empty() into the main function which seems to wake it up, letting it join and finish to completion. If that line is removed the entire thing goes back to waiting.

A bit weird, especially seeing as this has only been necessary on Ubuntu 13.04. I'm guessing it's something I'm doing in consuming the queue because juggling the queue is the process I understand the least and imposm.parser relies on the same functionality and seems to work just fine anywhere.

**Comment by aaronlidman** [comment]
Replaced .wait() with .terminate(). Works great, just finished North America.
